# Generated by Django 5.2.4 on 2025-08-02 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=8)),
                ('message', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('llm_context_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], max_length=2)),
                ('age_range', models.CharField(choices=[('U15', 'Under 15'), ('A15_19', '15–19'), ('A20_24', '20–24'), ('A25_34', '25–34'), ('A35_44', '35–44'), ('O45', '45+')], max_length=16)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=8)),
                ('interest_area', models.CharField(choices=[('CONTRACEPTION', 'Contraception'), ('MENSTRUATION', 'Menstruation'), ('PREGNANCY', 'Pregnancy'), ('STI_HIV', 'STIs & HIV'), ('CONSENT_REL', 'Consent & Healthy Relationships'), ('EMERGENCY', 'Emergency Support'), ('EXPLORING', 'Just exploring')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('VERY_HELPFUL', '👍🏾 Very helpful'), ('SOMEWHAT_HELPFUL', '🙂Somewhat helpful'), ('NOT_VERY', '😐Not very helpful'), ('NOT_HELPFUL', '👎🏾 Not helpful at all')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='bot.chatmessage')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.usersession'),
        ),
    ]
