# Generated by Django 5.2.4 on 2025-08-08 04:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_add_concurrent_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent', models.CharField(choices=[('ASK_INFO', 'Ask for Information'), ('ASK_ACTION', 'Ask for Action/Help'), ('REPORT_INCIDENT', 'Report an Incident'), ('EXPRESS_EMOTION', 'Express Emotion'), ('ASK_CONFIDENTIALITY', 'Ask for Confidentiality'), ('SEEK_VALIDATION', 'Seek Validation'), ('REFUSE_HELP', 'Refuse Help'), ('OTHER', 'Other')], max_length=32)),
                ('messages_analyzed', models.PositiveIntegerField(default=5, help_text='Number of messages analyzed for this classification')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence in classification (0-1)', null=True)),
                ('analysis_context', models.JSONField(blank=True, help_text='Context data used for classification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='bot.usersession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', '-created_at'], name='bot_classif_session_40fd4e_idx'), models.Index(fields=['intent'], name='bot_classif_intent_eb2a43_idx')],
            },
        ),
    ]
