# Generated by Django 5.2.4 on 2025-08-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_add_classification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='messages_analyzed',
            field=models.PositiveIntegerField(default=10, help_text='Number of messages analyzed for this classification'),
        ),
    ]
