# Generated by Django 5.2.4 on 2025-08-08 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_update_classification_default_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emotion_ratings', models.JSONField(help_text='Dictionary of emotion ratings: {emotion_code: rating(0-2)}')),
                ('primary_emotion', models.CharField(choices=[('FEAR', 'Fear'), ('SHAME', 'Shame'), ('CONFUSION', 'Confusion'), ('SADNESS', 'Sadness'), ('ANGER', 'Anger'), ('HELPLESSNESS', 'Helplessness'), ('NEUTRAL', 'Neutral')], help_text='The strongest emotion detected', max_length=32)),
                ('messages_analyzed', models.PositiveIntegerField(default=10, help_text='Number of messages analyzed for this emotion detection')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence in emotion detection (0-1)', null=True)),
                ('analysis_context', models.JSONField(blank=True, help_text='Context data used for emotion detection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='bot.usersession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', '-created_at'], name='bot_emotion_session_98cd78_idx'), models.Index(fields=['primary_emotion'], name='bot_emotion_primary_b9429c_idx')],
            },
        ),
    ]
