# Generated by Django 5.2.4 on 2025-08-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_add_emotion_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='region',
            field=models.CharField(blank=True, choices=[('ADDIS_ABABA', 'Addis Ababa City Administration'), ('AFAR', 'Afar Region'), ('AMHARA', 'Amhara Region'), ('BENISHANGUL', 'Benishangul-Gumuz Region'), ('CENTRAL_ETH', 'Central Ethiopia Region'), ('DIRE_DAWA', 'Dire Dawa City Administration'), ('GAMBELA', 'Gambela Region'), ('HARARI', 'Harari Region'), ('OROMIA', 'Oromia Region'), ('SIDAMA', 'Sidama Region'), ('SOUTH_ETH', 'South Ethiopia Region'), ('SOMALI', 'Somali Region'), ('SOUTHWEST', "South West Ethiopia Peoples' Region"), ('TIGRAY', 'Tigray Region')], max_length=32, null=True),
        ),
    ]
