# Generated by Django 5.2.4 on 2025-08-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_add_region_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True),
        ),
    ]
