# Generated by Django 5.2.4 on 2025-08-11 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_usersession_latitude_usersession_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('ABUSE', 'Physical/Sexual Abuse'), ('DOMESTIC_VIOLENCE', 'Domestic Violence'), ('SELF_HARM', 'Self-Harm/Suicide Risk'), ('ILLEGAL_ABORTION', 'Unsafe/Illegal Abortion'), ('SEXUAL_VIOLENCE', 'Sexual Violence/Rape'), ('UNSAFE_PRACTICES', 'Unsafe Sexual Practices'), ('CRISIS', 'Mental Health Crisis'), ('NEUTRAL', 'No Risk Detected')], help_text='The primary risk level detected', max_length=32)),
                ('risk_indicators', models.JSONField(blank=True, help_text='Specific indicators or keywords that triggered the risk assessment', null=True)),
                ('severity_score', models.FloatField(blank=True, help_text='Risk severity score (0-1, where 1 is highest risk)', null=True)),
                ('messages_analyzed', models.PositiveIntegerField(default=10, help_text='Number of messages analyzed for this risk assessment')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence in risk assessment (0-1)', null=True)),
                ('analysis_context', models.JSONField(blank=True, help_text='Context data used for risk assessment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='bot.usersession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', '-created_at'], name='bot_riskass_session_327f64_idx'), models.Index(fields=['risk_level'], name='bot_riskass_risk_le_df8ee4_idx'), models.Index(fields=['severity_score'], name='bot_riskass_severit_7832d8_idx')],
            },
        ),
    ]
